config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  post 'users/update'
  get 'users/login'
  get 'users/seed_login'
  get 'users/logout'
  post 'users/confirm2fa'
  post 'users/signup'

  get 'admin/dashboard'
  get 'admin/index'
  get 'admin/login'
  get 'admin/get_data'

  get 'page/index'
  get 'page/about'
  get 'page/help'
  get 'page/donate'

  get 'wallets/show'
  get 'wallets/seed_checker'
  get 'wallets/details'
  post 'wallets/add_addresses'
  get 'wallets/receive_addresses'

  get 'nodes/index'

  root 'page#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_time_password
  has_secure_password

  has_one :wallet

  validates :username, presence: true, uniqueness: true
  validates :wallet, presence: true
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user

  validates :encrypted_seed, presence: true
  validates :user, presence: true
end

app/controllers/admin_controller.rb
require 'json'


class AdminController < ApplicationController
  def get_data
    @admin = Admin.find_by_pk(params[:pk])
    unless @admin.nil?
      begin
        render json: get_stats.to_json
      rescue StandardError => error
        render json: { error: error.message }
      end
    end
  end

  def login
  end

  private

  def get_stats
    everything = {}

    everything[:num_wallets] = Wallet.count
    everything[:num_admins] = Admin.count
    everything[:num_wallets_created_last_day] = Wallet.where(created_at: 24.hours.ago..Time.now).count
    everything
  end
end

app/controllers/application_controller.rb
require 'authie/session'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from Authie::Session::InactiveSession, :with => :auth_session_error
  rescue_from Authie::Session::ExpiredSession, :with => :auth_session_error
  rescue_from Authie::Session::BrowserMismatch, :with => :auth_session_error

  private

  def auth_session_error
    redirect_to users_login_path
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end

  def help

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_session, only: [:show, :update]
  before_action :start_countdown

  after_action :delay_execution

  def seed_login
    # Used for UI related stuff
    session[:isLoggedIn] = true
  end

  def login
    if params.key?(:username)
      @user = User.find_by_username(params[:username])
      if @user.nil?
        return render json: { success: false, message: 'Invalid username or password' }
      end

      return unless authenticate_login_credentials(@user)
      return unless authenticate_2fa(@user)

      self.current_user = @user

      render json: { success: true, encrypted_seed: @user.wallet.encrypted_seed }
    else
      @user = User.new
    end
  end

  def signup
    @user = User.find_by_username(params[:username])
    unless @user.nil?
      return render json: { success: false, message: 'The username is taken' }
    end

    params[:has2fa] = params[:has2fa] == 'true'

    if create_user(params)
      self.current_user = @user

      if @user.has2fa
        render json: { success: true,
                       qr: get_qr(@user).as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 5)}
      else
        render json: { success: true }
      end
    else
      render json: { success: false, message: @user.errors.full_messages.to_sentence }
    end
  end

  def confirm2fa
    @user = User.find_by_username(params[:username])
    return unless authenticate_login_credentials(@user)

    if @user.authenticate_otp(params[:otp_key])
      @user.has_confirmed_2fa = true

      render json: { success: @user.save,
                     encrypted_seed: @user.wallet.encrypted_seed,
                     message: @user.errors.full_messages.to_sentence }

      self.current_user = @user unless @user.errors.any?
    else
      render json: { success: false, message: 'Invalid key. Try again' }
    end
  end

  def update
    return unless authenticate_2fa(current_user)
    attribs = params.permit(:has2fa, :has_confirmed_2fa)

    if current_user.update(attribs)
      render json: { success: true }
    else
      render json: { success: false, message: current_user.errors.full_messages.to_sentence }
    end
  end

  def logout
    if logged_in?
      # Will be false if the user is using a seed only.
      auth_session.invalidate!
    end
    reset_session
  end

  private

  def authenticate_login_credentials(user)
    if user.authenticate(params[:password])
      true
    else
      render json: { success: false, message: 'Invalid username or password' }
      false
    end
  end

  def authenticate_session
    unless logged_in?
      render json: { success: false, message: 'Invalid session' }
    end
  end

  def create_user(user_params)
    @user = User.new(username: user_params[:username], has2fa: user_params[:has2fa], password: user_params[:password])

    if @user.errors.none?
      @user.create_wallet(encrypted_seed: user_params[:encrypted_seed])
      @user.wallet.save!
      @user.save
    else
      false
    end
  end

  def get_qr(user)
    RQRCode::QRCode.new(user.provisioning_uri(user.username, issuer: 'IOTAWallet'),size: 10, level: :h)
  end

  def authenticate_2fa(user)
    return true unless user.has2fa

    unless user.has_confirmed_2fa
      render json: { success: false, require_2fa_confirmation: true,
                            qr: get_qr(user).as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 5) }
      return false
    end

    return true if params[:otp_key] && user.authenticate_otp(params[:otp_key])

    render json: { success: false, require_2fa: true }
    false
  end

  def validate_required_params(keys)
    keys.each do |key|
      unless params.key?(key)
        render json: { success: false, message: 'Missing ' + key }
        return false
      end
    end

    true
  end

  def start_countdown
    @start_time = Time.now
  end

  # Delays the execution of every action to take no less than 100 ms
  def delay_execution
    min_execution_time_secs = 0.1

    delay_time = [min_execution_time_secs - (Time.now - @start_time) * 1000.0, 0].max

    sleep delay_time
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_session, only: [:add_addresses]

  def add_addresses
    addresses = params[:addresses]
    return unless addresses

    wallet = current_user.wallet

    # Make sure we only have n addresses
    n = 10
    addresses = addresses.split(',')[0..n].join(',')

    wallet.receive_addresses = addresses
    wallet.save
  end

  def receive_addresses
    render json: { addresses: User.find_by_username(params[:username]).wallet.receive_addresses }
  end

  private

  def authenticate_session
    unless logged_in?
      render json: { success: false, message: 'Invalid session' }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pending_transactions_helper.rb
module PendingTransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/admin/dashboard.html.erb
<script>
    $( document ).ready(function() {
        loadAdminDashboardData();
    });
</script>

<h1>Dashboard</h1>
<div id="content"></div>

app/views/admin/index.html.erb
<h1>Login</h1>
<h2>Private key</h2>
<textarea class="form-control string" id="privkey" ></textarea>
<button onclick="loginAdmin()">Login</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IOTA wallet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'vendor/iota.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'vendor/curl.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'vendor/sjcl', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'vendor/md5.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="IOTA wallet is a free and open source online wallet for the distributed ledger IOTA">
    <meta name="author" content="Daniel Lind">

    <meta property="og:title" content="IOTA Wallet" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://iota-wallet.org" />
    <meta property="og:description" content="IOTA wallet is a free and open source online wallet for the distributed ledger IOTA" />
  </head>

  <body>
  <script>
    $(document).ready(function(){
      if (navigator.userAgent.indexOf('Safari') !== -1 && navigator.userAgent.indexOf('Chrome') === -1) {
          renderInfoAlert('mainNotifiactionArea',
              'This site does not currently work with safari. It will be supported very soon.');
      }
      try{curl}catch(err){
          renderInfoAlert('mainNotifiactionArea',
              'Your browser do not support WebGL2. Please enable it to use all our services');
      }

      try {
          loadGlobal();
          loadPolyfills();
      }catch (err){
          renderDangerAlert('mainNotifiactionArea',
              'Something went wrong. Please contact support if the problem persists. ' + err);
      }
    });

    $(document).on('turbolinks:load', function() {
        loadNodeInfoCached(onGetNodeStatusFinished);
    });
  </script>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul id="main_menu_nav" class="nav nav-pills pull-right">
            <li role="presentation" class=<%= 'active' if current_page?(root_path) %>><%= link_to "Home", root_path %></li>
            <% if logged_in? || session.key?('isLoggedIn') %>
              <li role="presentation" class=<%= 'active' if current_page?(wallets_show_path) || current_page?(wallets_details_path) %>><%= link_to "Wallet", wallets_show_path %></li>
            <% else %>
                <li role="presentation" class=<%= 'active' if current_page?(wallets_show_path) %>><%= link_to "Wallet", users_login_path %></li>
            <% end %>
            <% if logged_in? %>
                <li role="presentation" class=<%= 'active' if current_page?(users_show_path) %>><%= link_to "Account", users_show_path %></li>
          <% end %>
            <li role="presentation" class=<%= 'active' if current_page?(page_help_path) %>><%= link_to "Help", page_help_url %></li>
            <li role="presentation" class=<%= 'active' if current_page?(page_about_path) %>><%= link_to "About", page_about_url %></li>
            <% if logged_in? || session.key?('isLoggedIn') %>
              <li id="sign_out" role='presentation' ><a data-turbolinks="false" href='javascript:logOut();' ><span class='glyphicon glyphicon-log-out'></span></a></li>
            <% end %>
          </ul>
        </nav>
        <h3><a class="text-muted" href="/">IOTA Wallet</a></h3>
      </div>

      <div class="main-content">
        <div id="mainNotifiactionArea"></div>
        <%= yield %>
      </div>

      <footer class="footer">
        <div class="footer-content">
          <a href="/nodes/index" class="text-muted inline" id="node_status_wrapper" title="Not connected">Node status: <i class="fa fa-circle" id="node_status_symbol" aria-hidden="true"></i></a>
        </div>
      </footer>

    </div> <!-- /container -->
  </body>

</html>

app/views/nodes/index.html.erb
<script>
    $(document).on('turbolinks:load', function() {
        // Because turbolinks breaks the normal jquery behaviour, this will fire for all pages after the wallet has been visited
        // Only want to proceed it the current page is wallet/show
        if (window.location.href.indexOf('nodes/index') === -1){
            return;
        }

        loadNodeInfo(onGetNodeInfoFinished);
        $(document).find('#node-data').hide();
        $("#loading").spin({
            color: '#777',
            top: '40%',
            length: 20,
            width: 15,
            radius: 30
        });
    });
</script>

<div id="node-status"></div>

<div id="loading" ><p class="text-muted">Loading node...</p></div>

<div id="node-data">
  <h1>Node information</h1>
  <table class="table" id="node-info">
    <tbody id="node_info_table">
    </tbody>
  </table>
</div>

app/views/page/_index.html.erb
<style>
  .jumbotron {
    background-color: transparent;
  }
  .jumbotron h1 {
    font-size: 2.9em;
  }
</style>

<section class="jumbotron text-center">
  <div class="container">
    <p><%= image_tag 'iota_logo.png', size: 100 %></p>
    <h1>IOTA web wallet</h1>
    <p>A secure and user friendly IOTA wallet</p>
    <% if logged_in? || session.key?('isLoggedIn') %>
        <div id="open_wallet">
          <%= link_to "Go to wallet", wallets_show_path, :class=>"btn btn-primary", :type=>"button" %>
        </div>
    <% else %>
        </div>
        <div id="sign_in">
          <%= link_to "Sign in", users_login_path, :class=>"btn btn-primary", :type=>"button" %>
          <%= link_to "New user", users_login_path, :class=>"btn btn-default", :type=>"button" %>
        </div>
    <% end %>
</section>

<div class="row">
  <div class="col-md-4">
    <h2>Secure</h2>
    <p>We don't store any sensitive information about you. In fact, your seed and password never even leaves your client.
      This means your wallet is completely safe with our services</p>
  </div>
  <div class="col-md-4">
    <h2>User friendly</h2>
    <p>Our aim is to make IOTA as user friendly as possible. We handle the complexities, and provide you with a simple interface to the IOTA network.</p>
  </div>
  <div class="col-md-4">
    <h2>Compatible</h2>
    <p>All IOTA wallets are compatible with each other. If you want to switch from one wallet to another, all you need is your seed.</p>
  </div>
</div>

app/views/page/about.html.erb
<h1>About</h1>
<p>IOTA wallet is a open source tool that provides an easy and user friendly wallet for the distributed ledger <a href="iota.org">IOTA</a></p>
<p>The tool was created by <a href="https://github.com/danilind" >danilind</a>. The source code is publicly available on
  <a href="https://github.com/danilind/iota-web-wallet" >github</a> </p>

<h2>Contact</h2>
<ul>
  <li>Mail: <a href="mailto:support@iota-wallet.org">support@iota-wallet.org</a></li>
  <li>Github: <a href="https://github.com/danilind/iota-web-wallet">Github</a></li>
</ul>

<h2>Donations</h2>
Donations help keep this site running. Go to <a href="/page/donate">donations</a>

<h2>Bugs</h2>
If you find bugs, send us a mail or open a github issue

app/views/page/donate.html.erb
<h1>Support us</h1>
<div>
  <p>If you want to show your support and help keep this site running, donations are much appreciated. You can donate IOTA, ETH or BTC</p>
  <table class="table fixed-table">
    <thead>
    <tr>
      <th style="width: 7em;"></th>
      <th>Address</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><b>IOTA</b></td>
      <td>PRADUTNZ99BATVWNMCEHTUXATWVLTPVCQQBJYDIAHPQDAQDDQELWKS9PLHTCLNJYVB9ENJAINLQWOFVLXTHAHMKKFF</td>
    </tr>
    <tr>
      <td><b>ETH</b></td>
      <td>0x0b9b1E299727a656b268C04d61E3349d6adA86b2</td>
    </tr>
    <tr>
      <td><b>BTC</b></td>
      <td>1PKLe6xmwJhs9hkqi8czefx4vBDSGhiCVV</td>
    </tr>
    </tbody>
  </table>
</div>

app/views/page/help.html.erb
<h1>FAQ</h1>
<div class="container">
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse1">Do I need an account?</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <div class="panel-body">
          No. You can access your wallet using an account, or using your seed alone.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapsewbgl">How do I enable WebGL2?</a>
        </h4>
      </div>
      <div id="collapsewbgl" class="panel-collapse collapse">
        <div class="panel-body">
          WebGL2 is required to make transactions and to generate new addresses. If you get a message telling you to
          enable webgl2, try the steps in https://get.webgl.org/webgl2/enable.html. You also have to make sure that
          hardware acceleration is enabled in your browser. If none of the previous steps works, your device may not support WebGL2.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse2">I lost my password. What do I do?</a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="panel-body">
          We don't store your password, and will not be able to retrieve it. If you still have your seed, you can use it
          to access your account.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse13">Transactions and address generation takes forever. Why?</a>
        </h4>
      </div>
      <div id="collapse13" class="panel-collapse collapse">
        <div class="panel-body">
          <p>When making a transaction, your browser has to do proof of work. This is similar to what bitcoin miners have
            to do, but with IOTA this is done by the senders. If your computer is slow, this could take some time.</p>
          <p>Another thing to be aware of is that some browsers reduce the processing power of tabs when you leave them.
            You should therefore make sure to stay on the site until the work is done (sadly, we do not control this). </p>
          <p>Another approach for chrome users would be to do the transaction in a new window instead of a new tab. As
            long as the tab is selected in the new window, you are free to browse in the original chrome window without
            reducing processing power.</p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse14">My balance is gone/too low</a>
        </h4>
      </div>
      <div id="collapse14" class="panel-collapse collapse">
        <div class="panel-body">
          <p>There can be 2 reasons for this.</p>
          <p>Your IOTAs are stored on addresses, which again belong to your seed. When you enter the wallet, it will
            load up to 30 of your last addresses. If you have more than 30 addresses, and some of the first ones have a
            positive balance, the seed balance will be wrong. </p><p><b>Solution: </b>This can easily be fixed by pressing the "Load all"
            button in your wallet. Consider moving all your funds to one address when this happens.</p>
          <p>Another reason why the balance may not show up is if there has recently been a snapshot on the IOTA network.
          When a snapshot is taken, all unnecessary data is basically removed from the network. The result is that
            the wallet sometimes won't be able to find all your addresses. </p>
          </p><p><b>Solution: </b>Press the "Generate new address" button until your balance is correct.</p>
        </div>
      </div>
    </div>

    <div class="faqHeader">Security</div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse3">Is this secure?</a>
        </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
        <div class="panel-body">
          No sensitive information ever leaves your client. If you register an account your seed immediately gets
          encrypted before it is transferred to our server. That means we will never be able to restore your seed if you
          loose it or your login credentials.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse4">What happens if I lose my seed?</a>
        </h4>
      </div>
      <div id="collapse4" class="panel-collapse collapse">
        <div class="panel-body">
          <p>If you lose your seed and do not have a account, your iotas are gone.</p>
          <p>It is always advised that you keep a backup of your seed somewhere safe</p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse5">Is my seed safe with you?</a>
        </h4>
      </div>
      <div id="collapse5" class="panel-collapse collapse">
        <div class="panel-body">
          We never get access to your seed. Every action that require a seed is made locally on your device.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse6">What happens if the site goes down?</a>
        </h4>
      </div>
      <div id="collapse6" class="panel-collapse collapse">
        <div class="panel-body">
          Then you will still be able to access your IOTA account if you have your seed. You can for example use the desktop wallet.
        </div>
      </div>
    </div>

  <div class="faqHeader">IOTA</div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse9">What is IOTA?</a>
      </h4>
    </div>
    <div id="collapse9" class="panel-collapse collapse">
      <div class="panel-body">
        IOTA is a distributed ledger capable of fee less transactions and infinite scaling. Check our these links for
        more in depth information:
        <ul>
          <li><a href="http://www.iotasupport.com/whatisiota.shtml">iotasupport</a></li>
          <li><a href="http://www.tangleblog.com/what-is-iota-what-is-the-tangle/">tangleblog</a></li>
          <li><a href="http://www.tangleblog.com/2017/06/05/ama-answers-for-newcomers/">tangleblog faq</a></li>
        </ul>
      </div>
    </div>
  </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse11">What does it mean to replay/re-attach?</a>
        </h4>
      </div>
      <div id="collapse11" class="panel-collapse collapse">
        <div class="panel-body">
          <p>When you replay a transaction, it is basically moved to a different part of the tangle, which may be more active.
            The reason for doing this is to increase the chances of it being picked up and validated by others</p>
          <p>iota-wallet.org replays/re-attaches your transactions automatically, so you don't normally have to think
            about it. If you on the other hand have a transaction that have been pending for a long time, you may want
            to replay it yourself.</p>
          <p> Also note the we don't allow you to replay double spends, because they can never be confirmed.</p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse15">What is a double spend?</a>
      </h4>
    </div>
    <div id="collapse15" class="panel-collapse collapse">
      <div class="panel-body">
        <p>IOTA addresses become insecure to use after it has been used to make a transaction. Because of this, this is what happens when you make a transaction:</p>
        <ul>
          <li>A list of your addresses with a positive balance is collected, and is used to fund the transaction</li>
          <li>The transaction is made by doing proof of work. You validate two other transactions at the same time</li>
          <li>All remaining funds on the addresses used in step 1 are transferred to a newly generated address</li>
        </ul>
        <p>What this means is that if you send two transactions from the same address, one of them will be confirmed,
          and the addresses will have a balance of 0. The remaining transaction will therefore never be confirmed, because
          it doesn't have enough funds</p>
        <p>If this happens, the solution is simple: Do the pending transaction again. iota-wallet.org provides a warning
          before every attempt to double spend. If you get such a warning, simply wait until the last outgoing transaction
          has been confirmed</p>
      </div>
    </div>
  </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse12">Should I re-attach or make the transaction again?</a>
        </h4>
      </div>
      <div id="collapse12" class="panel-collapse collapse">
        <div class="panel-body">
          By opening the transaction, one of the following will be true:
          <ul>
            <li>You see a green re-attach button. </li>
            <li>You get a red warning telling you that the transaction is a double spend. In that case you will have to do the transaction again manually</li>
          </ul>
          iota-wallet.org replays your transactions automatically, but if it has been pending a long time and it is not
          a double spend, you can choose to replay it yourself.
        </div>
      </div>
    </div>
  </div>
</div>

<h1>Support</h1>
<p>Still having questions? Get in touch: </p>
<ul>
  <li><a href="https://github.com/danilind/iota-web-wallet">Github</a></li>
  <li>Email: <a href="mailto:support@iota-wallet.org">support@iota-wallet.org</a></li>
</ul>

<style>
  .faqHeader {
    font-size: 1.7em;
    margin: 20px;
  }
</style>

app/views/page/index.html.erb
<%= render 'index' %>

app/views/users/_account.html.erb
<ul class="list-group">
  <li class="list-group-item text-muted"><h2>Your account</h2></li>
  <li class="list-group-item text-right">
    <span class="pull-left">
      <strong>Username</strong>
    </span><%= current_user.username %></li>
  <li class="list-group-item text-right">
    <span class="pull-left">
      <strong>Joined</strong>
    </span> <%= current_user.created_at.localtime %></li>
  <li class="list-group-item text-right">
    <span class="pull-left">
      <strong>Two-factor authentication</strong>
    </span> <%= if current_user.has2fa then 'Enabled' else 'Disabled' end %></li>
</ul>

<style>
  .list-group-item{
    background-color: transparent;
    max-width: 30em;
  }
</style>

app/views/users/_confirm2fa.html.erb
<script>
    $( document ).ready(function() {
        $("#otp_key_signup").keyup(function (event) {
            if (event.keyCode === 13) {
                $("#confirm2fa").click();
            }
        })
    });
</script>

<h1>Confirm two-factor authentication</h1>

<div id="qr">
</div>

<form class="form-inline" style="padding-top: 1em">
  <div class="form-group">
    <label for="otp_key_signup">Code:</label>
    <input type="text" class="form-control" id="otp_key_signup" placeholder="Enter key" >
  </div>
  <button class="ladda-button btn btn-primary btn" data-style="expand-right" id="confirm2fa" onclick="onConfirm2faClick(this)">
    <span class="ladda-label">Confirm</span>
  </button>
  <div class="text-muted">Please scan the QR code above and enter your authenticator code</div>
</form>

app/views/users/login.html.erb
<script>
    $( document ).ready(function() {
        $('#loginModal').modal('show')
    });
</script>

<%= render 'page/index' %>
<div class="modal fade" tabindex="-1" role="dialog" id="loginModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Open wallet</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Close', page_index_path, type: 'button', clas: 'btn' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->